on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build Crews.PlanningCenter.Api --configuration Release
    - name: Test
      run: dotnet test Crews.PlanningCenter.Api.Tests --configuration Release